### ISSUE TITLE
Sidecar pod is NOT booting up

### ISSUE THREAD

**Issue by jaikratsinghtariyal** [svenbernhardt/service-integration-made-easy#1]
@svenbernhardt ... can you please check ticket raised at 

- https://github.com/kumahq/kuma-demo/issues/128
- https://github.com/kumahq/kuma/issues/2814

**Comment by jaikratsinghtariyal** [comment]
Issue is resolved after I switched to minikube way of kubernetes

**Comment by svenbernhardt** [comment]
Great, but also strange that is not working properly with k3d.

Since you resolved it, I'll close the issue.
